
package Dashboard;

import Visual.*;
//import Visual.Principal;
//import Visual.Usuarios;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;
import Visual.Clientes;
import javax.swing.JOptionPane;

public class Menú extends javax.swing.JFrame {

    int xMouse, yMouse;
    public Menú() {
        initComponents();
        SetDate();
        InitContent();
        this.setSize(new Dimension(1020, 400));
        this.setTitle("Menu");
    }
    
    private void SetDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale ("es", "ES");
        datetxt.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy")));

    }
    
    private void InitContent() {
        ShowJPanel(new Principal());
    }
    
    public static void ShowJPanel (JPanel p) {
        p.setSize(780, 520);
        p.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        pprincipal = new javax.swing.JPanel();
        principaltxt = new javax.swing.JLabel();
        prenta = new javax.swing.JPanel();
        rentatxt = new javax.swing.JLabel();
        pclientes = new javax.swing.JPanel();
        clientestxt = new javax.swing.JLabel();
        pmaquinas = new javax.swing.JPanel();
        maquinastxt = new javax.swing.JLabel();
        pusuarios = new javax.swing.JPanel();
        usuariostxt = new javax.swing.JLabel();
        poperarios = new javax.swing.JPanel();
        operariostxt = new javax.swing.JLabel();
        preportes = new javax.swing.JPanel();
        reportestxt = new javax.swing.JLabel();
        pfacturas = new javax.swing.JPanel();
        phistorial = new javax.swing.JPanel();
        historialtxt = new javax.swing.JLabel();
        facturastxt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        datetxt = new javax.swing.JLabel();
        popciones = new javax.swing.JPanel();
        psalir = new javax.swing.JPanel();
        salirtxt = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1020, 640));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(222, 137, 21));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(240, 150, 35));

        pprincipal.setBackground(new java.awt.Color(240, 150, 35));

        principaltxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        principaltxt.setForeground(new java.awt.Color(255, 255, 255));
        principaltxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        principaltxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        principaltxt.setText("     Principal               >");
        principaltxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principaltxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principaltxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                principaltxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                principaltxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pprincipalLayout = new javax.swing.GroupLayout(pprincipal);
        pprincipal.setLayout(pprincipalLayout);
        pprincipalLayout.setHorizontalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pprincipalLayout.createSequentialGroup()
                .addComponent(principaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pprincipalLayout.setVerticalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principaltxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        prenta.setBackground(new java.awt.Color(240, 150, 35));

        rentatxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        rentatxt.setForeground(new java.awt.Color(255, 255, 255));
        rentatxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentatxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dollar.png"))); // NOI18N
        rentatxt.setText("     Renta                   >");
        rentatxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rentatxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentatxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rentatxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rentatxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout prentaLayout = new javax.swing.GroupLayout(prenta);
        prenta.setLayout(prentaLayout);
        prentaLayout.setHorizontalGroup(
            prentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prentaLayout.createSequentialGroup()
                .addComponent(rentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        prentaLayout.setVerticalGroup(
            prentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pclientes.setBackground(new java.awt.Color(240, 150, 35));

        clientestxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        clientestxt.setForeground(new java.awt.Color(255, 255, 255));
        clientestxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clientestxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/users-alt.png"))); // NOI18N
        clientestxt.setText("     Clientes                >");
        clientestxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientestxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientestxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientestxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientestxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pclientesLayout = new javax.swing.GroupLayout(pclientes);
        pclientes.setLayout(pclientesLayout);
        pclientesLayout.setHorizontalGroup(
            pclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pclientesLayout.createSequentialGroup()
                .addComponent(clientestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pclientesLayout.setVerticalGroup(
            pclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pclientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clientestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pmaquinas.setBackground(new java.awt.Color(240, 150, 35));

        maquinastxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        maquinastxt.setForeground(new java.awt.Color(255, 255, 255));
        maquinastxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maquinastxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/truck-side.png"))); // NOI18N
        maquinastxt.setText("     Máquinas              >");
        maquinastxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maquinastxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maquinastxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maquinastxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maquinastxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pmaquinasLayout = new javax.swing.GroupLayout(pmaquinas);
        pmaquinas.setLayout(pmaquinasLayout);
        pmaquinasLayout.setHorizontalGroup(
            pmaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmaquinasLayout.createSequentialGroup()
                .addComponent(maquinastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pmaquinasLayout.setVerticalGroup(
            pmaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmaquinasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(maquinastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pusuarios.setBackground(new java.awt.Color(240, 150, 35));

        usuariostxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        usuariostxt.setForeground(new java.awt.Color(255, 255, 255));
        usuariostxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usuariostxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        usuariostxt.setText("     Usuarios               >");
        usuariostxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuariostxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariostxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuariostxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuariostxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pusuariosLayout = new javax.swing.GroupLayout(pusuarios);
        pusuarios.setLayout(pusuariosLayout);
        pusuariosLayout.setHorizontalGroup(
            pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pusuariosLayout.createSequentialGroup()
                .addComponent(usuariostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pusuariosLayout.setVerticalGroup(
            pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pusuariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(usuariostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        poperarios.setBackground(new java.awt.Color(240, 150, 35));

        operariostxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        operariostxt.setForeground(new java.awt.Color(255, 255, 255));
        operariostxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        operariostxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fingerprint (1).png"))); // NOI18N
        operariostxt.setText("     Operarios               >");
        operariostxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operariostxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                operariostxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                operariostxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout poperariosLayout = new javax.swing.GroupLayout(poperarios);
        poperarios.setLayout(poperariosLayout);
        poperariosLayout.setHorizontalGroup(
            poperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(operariostxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        poperariosLayout.setVerticalGroup(
            poperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(operariostxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        preportes.setBackground(new java.awt.Color(240, 150, 35));

        reportestxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        reportestxt.setForeground(new java.awt.Color(255, 255, 255));
        reportestxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reportestxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        reportestxt.setText("     Reportes               >");
        reportestxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportestxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportestxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportestxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout preportesLayout = new javax.swing.GroupLayout(preportes);
        preportes.setLayout(preportesLayout);
        preportesLayout.setHorizontalGroup(
            preportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preportesLayout.createSequentialGroup()
                .addComponent(reportestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        preportesLayout.setVerticalGroup(
            preportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preportesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reportestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pfacturas.setBackground(new java.awt.Color(240, 150, 35));

        javax.swing.GroupLayout pfacturasLayout = new javax.swing.GroupLayout(pfacturas);
        pfacturas.setLayout(pfacturasLayout);
        pfacturasLayout.setHorizontalGroup(
            pfacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pfacturasLayout.setVerticalGroup(
            pfacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        phistorial.setBackground(new java.awt.Color(240, 150, 35));

        historialtxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        historialtxt.setForeground(new java.awt.Color(255, 255, 255));
        historialtxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        historialtxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-histogram.png"))); // NOI18N
        historialtxt.setText("     Historial               >");
        historialtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historialtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historialtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historialtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout phistorialLayout = new javax.swing.GroupLayout(phistorial);
        phistorial.setLayout(phistorialLayout);
        phistorialLayout.setHorizontalGroup(
            phistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historialtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        phistorialLayout.setVerticalGroup(
            phistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phistorialLayout.createSequentialGroup()
                .addComponent(historialtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        facturastxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        facturastxt.setForeground(new java.awt.Color(255, 255, 255));
        facturastxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        facturastxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document.png"))); // NOI18N
        facturastxt.setText("     Facturas               >");
        facturastxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facturastxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facturastxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facturastxtMouseExited(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(240, 150, 35));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        jLabel2.setText("  Cerrar Sesion  ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(prenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pmaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(preportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(facturastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poperarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phistorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(prenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pmaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(poperarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(preportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pfacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facturastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre de la empresa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 640));

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        datetxt.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        datetxt.setForeground(new java.awt.Color(255, 255, 255));
        datetxt.setText("Hoy es: {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 780, 70));

        popciones.setBackground(new java.awt.Color(255, 255, 255));
        popciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                popcionesMouseDragged(evt);
            }
        });
        popciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popcionesMousePressed(evt);
            }
        });

        psalir.setBackground(new java.awt.Color(255, 255, 255));

        salirtxt.setBackground(new java.awt.Color(255, 255, 255));
        salirtxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        salirtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirtxt.setText("x");
        salirtxt.setAutoscrolls(true);
        salirtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirtxt.setInheritsPopupMenu(false);
        salirtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout psalirLayout = new javax.swing.GroupLayout(psalir);
        psalir.setLayout(psalirLayout);
        psalirLayout.setHorizontalGroup(
            psalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salirtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );
        psalirLayout.setVerticalGroup(
            psalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout popcionesLayout = new javax.swing.GroupLayout(popciones);
        popciones.setLayout(popcionesLayout);
        popcionesLayout.setHorizontalGroup(
            popcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popcionesLayout.createSequentialGroup()
                .addContainerGap(971, Short.MAX_VALUE)
                .addComponent(psalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        popcionesLayout.setVerticalGroup(
            popcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(popciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setRequestFocusEnabled(false);

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        Background.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 114, 780, 520));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        Background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 740, 460));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void principaltxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principaltxtMouseEntered
        pprincipal.setBackground(new Color (255, 160, 30));       
    }//GEN-LAST:event_principaltxtMouseEntered

    private void principaltxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principaltxtMouseExited
        pprincipal.setBackground(new Color (240, 150, 35));
    }//GEN-LAST:event_principaltxtMouseExited

    private void rentatxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentatxtMouseEntered
        prenta.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_rentatxtMouseEntered

    private void rentatxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentatxtMouseExited
        prenta.setBackground(new Color (240, 150, 35));
    }//GEN-LAST:event_rentatxtMouseExited

    private void clientestxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientestxtMouseEntered
        pclientes.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_clientestxtMouseEntered

    private void clientestxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientestxtMouseExited
        pclientes.setBackground(new Color (240, 150, 35));
    }//GEN-LAST:event_clientestxtMouseExited

    private void maquinastxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maquinastxtMouseEntered
        pmaquinas.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_maquinastxtMouseEntered

    private void maquinastxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maquinastxtMouseExited
        pmaquinas.setBackground(new Color (240, 150, 35));
    }//GEN-LAST:event_maquinastxtMouseExited

    private void usuariostxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariostxtMouseEntered
        pusuarios.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_usuariostxtMouseEntered

    private void usuariostxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariostxtMouseExited
        pusuarios.setBackground(new Color (240, 150, 35));
    }//GEN-LAST:event_usuariostxtMouseExited

    private void reportestxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportestxtMouseEntered
        poperarios.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_reportestxtMouseEntered

    private void reportestxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportestxtMouseExited
        poperarios.setBackground(new Color (240, 150, 35));
    }//GEN-LAST:event_reportestxtMouseExited

    private void facturastxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturastxtMouseEntered
        preportes.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_facturastxtMouseEntered

    private void facturastxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturastxtMouseExited
        preportes.setBackground(new Color (240, 150, 35)); 
    }//GEN-LAST:event_facturastxtMouseExited

    private void principaltxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principaltxtMouseClicked
        ShowJPanel(new Principal());     
    }//GEN-LAST:event_principaltxtMouseClicked

    private void rentatxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentatxtMouseClicked
        ShowJPanel(new RentaVista()); 
    }//GEN-LAST:event_rentatxtMouseClicked

    private void salirtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirtxtMouseEntered
        psalir.setBackground(Color.red);
        salirtxt.setForeground(Color.white);
    }//GEN-LAST:event_salirtxtMouseEntered

    private void salirtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirtxtMouseExited
        psalir.setBackground(Color.white);
        salirtxt.setForeground(Color.black);
    }//GEN-LAST:event_salirtxtMouseExited

    private void popcionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popcionesMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_popcionesMousePressed

    private void popcionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popcionesMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_popcionesMouseDragged

    private void salirtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirtxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirtxtMouseClicked

    private void usuariostxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariostxtMouseClicked
        ShowJPanel(new MenuUsuarios());
    }//GEN-LAST:event_usuariostxtMouseClicked

    private void clientestxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientestxtMouseClicked
        ShowJPanel(new MenuClientes());
    }//GEN-LAST:event_clientestxtMouseClicked

    private void maquinastxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maquinastxtMouseClicked
        ShowJPanel(new MenuMaquinas());
    }//GEN-LAST:event_maquinastxtMouseClicked

    private void historialtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialtxtMouseExited
        pfacturas.setBackground(new Color (240, 150, 35));
    }//GEN-LAST:event_historialtxtMouseExited

    private void historialtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialtxtMouseEntered
        pfacturas.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_historialtxtMouseEntered

    private void operariostxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operariostxtMouseEntered
         poperarios.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_operariostxtMouseEntered

    private void operariostxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operariostxtMouseExited
         poperarios.setBackground(new Color (240, 150, 35)); 
    }//GEN-LAST:event_operariostxtMouseExited

    private void operariostxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operariostxtMouseClicked
        ShowJPanel(new MenuOperarios());
    }//GEN-LAST:event_operariostxtMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            Login frmLogin = new Login();
            frmLogin.setVisible(true);
            this.setVisible(false); // Cierra el FrmMenu
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void historialtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialtxtMouseClicked
        // TODO add your handling code here:
        ShowJPanel(new MenuHistorial());
    }//GEN-LAST:event_historialtxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menú().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel clientestxt;
    private static javax.swing.JPanel contenido;
    private javax.swing.JLabel datetxt;
    private javax.swing.JLabel facturastxt;
    private javax.swing.JLabel historialtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maquinastxt;
    private javax.swing.JLabel operariostxt;
    private javax.swing.JPanel pclientes;
    private javax.swing.JPanel pfacturas;
    private javax.swing.JPanel phistorial;
    private javax.swing.JPanel pmaquinas;
    private javax.swing.JPanel popciones;
    private javax.swing.JPanel poperarios;
    private javax.swing.JPanel pprincipal;
    private javax.swing.JPanel prenta;
    private javax.swing.JPanel preportes;
    private javax.swing.JLabel principaltxt;
    private javax.swing.JPanel psalir;
    private javax.swing.JPanel pusuarios;
    private javax.swing.JLabel rentatxt;
    private javax.swing.JLabel reportestxt;
    private javax.swing.JLabel salirtxt;
    private javax.swing.JLabel usuariostxt;
    // End of variables declaration//GEN-END:variables

    public void Menu() {
        usuariostxt.setVisible(false);
        operariostxt.setVisible(false);
        maquinastxt.setVisible(false);
        //historialtxt.setVisible(false);
    }
}
