CREATE TABLE IF NOT EXISTS clientes (
    id_cliente integer PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    direccion varchar(150) NOT NULL,
    telefono varchar(30) NOT NULL,
    email varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS operarios (
    id_operario integer PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    direccion varchar(150) NOT NULL,
    telefono varchar(30) NOT NULL,
    email varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS maquinaria (
    id_maquinaria integer PRIMARY KEY,
    tipo varchar(80) NOT NULL,
    marca varchar(80) NOT NULL,
    modelo integer NOT NULL,
    fecha_adquisicion date NOT NULL,
    costo_renta_dia numeric(12,2) NOT NULL CHECK (costo_renta_dia >= 0),
    estatus varchar(30) NOT NULL DEFAULT 'Disponible'
);

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario integer PRIMARY KEY,
    nom_usuario varchar(100) NOT NULL,
    tipo_usuario varchar(30) NOT NULL,
    usuario varchar(60) NOT NULL UNIQUE,
    password varchar(80) NOT NULL,
    telefono varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS renta (
    id_renta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_maquinaria integer NOT NULL REFERENCES maquinaria(id_maquinaria),
    id_cliente integer NOT NULL REFERENCES clientes(id_cliente),
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    costo_total numeric(12,2) NOT NULL CHECK (costo_total >= 0),
    CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE IF NOT EXISTS operaciones (
    id_operacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_maquinaria integer NOT NULL REFERENCES maquinaria(id_maquinaria),
    id_operario integer NOT NULL REFERENCES operarios(id_operario),
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    CHECK (fecha_fin >= fecha_inicio)
);

INSERT INTO usuario (id_usuario, nom_usuario, tipo_usuario, usuario, password, telefono) VALUES
    (1, 'Administrador Demo', 'Administrador', 'admin', 'admin123', '555-100-0001'),
    (2, 'Usuario Demo', 'Usuario', 'usuario', 'usuario123', '555-100-0002')
ON CONFLICT (id_usuario) DO NOTHING;

INSERT INTO clientes (id_cliente, nombre, direccion, telefono, email) VALUES
    (1, 'Constructora Aula Norte', 'Av. Universidad 120, Centro', '555-210-1001', 'contacto@aulanorte.test'),
    (2, 'Obras Escolares Rivera', 'Calle Reforma 45, Col. Industrial', '555-210-1002', 'obras@rivera.test'),
    (3, 'Servicios de Terraceria Lopez', 'Camino Real 88, Zona Sur', '555-210-1003', 'terreceria.lopez@test.com')
ON CONFLICT (id_cliente) DO NOTHING;

INSERT INTO operarios (id_operario, nombre, direccion, telefono, email) VALUES
    (1, 'Carlos Medina', 'Calle Roble 14', '555-310-2001', 'carlos.medina@test.com'),
    (2, 'Mariana Torres', 'Av. Hidalgo 67', '555-310-2002', 'mariana.torres@test.com'),
    (3, 'Jorge Salas', 'Privada Morelos 22', '555-310-2003', 'jorge.salas@test.com')
ON CONFLICT (id_operario) DO NOTHING;

INSERT INTO maquinaria (id_maquinaria, tipo, marca, modelo, fecha_adquisicion, costo_renta_dia, estatus) VALUES
    (1, 'Excavadora', 'Caterpillar', 2020, '2021-03-15', 3500.00, 'Disponible'),
    (2, 'Retroexcavadora', 'John Deere', 2019, '2020-07-10', 2800.00, 'Disponible'),
    (3, 'Montacargas', 'Toyota', 2021, '2022-01-20', 1800.00, 'Disponible'),
    (4, 'Compactadora', 'Bomag', 2018, '2019-11-05', 2200.00, 'Mantenimiento')
ON CONFLICT (id_maquinaria) DO NOTHING;

INSERT INTO renta (id_renta, id_maquinaria, id_cliente, fecha_inicio, fecha_fin, costo_total) OVERRIDING SYSTEM VALUE VALUES
    (1, 1, 1, '2026-05-01', '2026-05-03', 10500.00)
ON CONFLICT (id_renta) DO NOTHING;

INSERT INTO operaciones (id_operacion, id_maquinaria, id_operario, fecha_inicio, fecha_fin) OVERRIDING SYSTEM VALUE VALUES
    (1, 1, 1, '2026-05-01', '2026-05-03')
ON CONFLICT (id_operacion) DO NOTHING;

UPDATE maquinaria SET estatus = 'Alquilada' WHERE id_maquinaria = 1;

SELECT setval(pg_get_serial_sequence('renta', 'id_renta'), COALESCE((SELECT MAX(id_renta) FROM renta), 1), true);
SELECT setval(pg_get_serial_sequence('operaciones', 'id_operacion'), COALESCE((SELECT MAX(id_operacion) FROM operaciones), 1), true);
