
package Visual;

import java.awt.Color;
import Modelo.Maquina;
import Controlador.Ctrl_Maquina;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class IngresarMaquina extends javax.swing.JPanel {

    /**
     * Creates new form GestionarUsuarios
     */
    public IngresarMaquina() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_marca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        pregistrar = new javax.swing.JPanel();
        registrartxt = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        txt_fecha = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(735, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setText("Crear nueva Maquina");

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Marca:");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID:");

        txt_id.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_id.setForeground(new java.awt.Color(204, 204, 204));
        txt_id.setBorder(null);
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 133, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 133, 0));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel5.setText("Modelo:");

        txt_modelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(204, 204, 204));
        txt_modelo.setBorder(null);
        txt_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modeloKeyTyped(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 133, 0));

        txt_marca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_marca.setForeground(new java.awt.Color(204, 204, 204));
        txt_marca.setBorder(null);
        txt_marca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_marcaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txt_id)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(txt_marca))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Adquisicion:");

        jSeparator4.setForeground(new java.awt.Color(255, 133, 0));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel7.setText("Precio de Renta:");

        txt_precio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_precio.setForeground(new java.awt.Color(204, 204, 204));
        txt_precio.setBorder(null);
        txt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precioKeyTyped(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 133, 0));

        pregistrar.setBackground(new java.awt.Color(255, 153, 0));

        registrartxt.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        registrartxt.setForeground(new java.awt.Color(255, 255, 255));
        registrartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrartxt.setText("Registrar");
        registrartxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrartxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrartxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrartxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrartxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pregistrarLayout = new javax.swing.GroupLayout(pregistrar);
        pregistrar.setLayout(pregistrarLayout);
        pregistrarLayout.setHorizontalGroup(
            pregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrartxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        pregistrarLayout.setVerticalGroup(
            pregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrartxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jSeparator6.setForeground(new java.awt.Color(255, 133, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel4.setText("Tipo:");

        combotipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el tipo de maquina", "Bulldozer", "Excavadora", "Miniexcavadora", "Retroexcavadora", "Minicargador", "Motoniveladoras", "Camiones articulados" }));
        combotipo.setBorder(null);
        combotipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 171, Short.MAX_VALUE)
                .addComponent(pregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jSeparator4)
                    .addComponent(txt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combotipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(pregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 390, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void registrartxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrartxtMouseEntered
        pregistrar.setBackground(new Color(240, 140, 40));
    }//GEN-LAST:event_registrartxtMouseEntered

    private void registrartxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrartxtMouseExited
        pregistrar.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_registrartxtMouseExited

    private void registrartxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrartxtMouseClicked
        
        Maquina maquina = new Maquina();
        Ctrl_Maquina controlmaquina = new Ctrl_Maquina();
        
        String tipomaquina="";
        String fecha="";
        String estatus="Disponible";
        
        java.util.Date date = new java.util.Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        
        tipomaquina=combotipo.getSelectedItem().toString().trim();
        fecha = f.format(txt_fecha.getDate());
        
        //System.out.println("La fecha que puse es " + fecha);
        
        
        if(txt_id.getText().equals("")|| txt_marca.getText().equals("")|| txt_modelo.getText().equals("")|| txt_precio.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }else{
            
            if(!controlmaquina.existeMaquina(txt_id.getText().trim())){
                
                if(tipomaquina.equalsIgnoreCase("Selecciona el tipo de maquina")){
                    JOptionPane.showMessageDialog(null, "Selecciona el tipo de maquina");   
                }else{
                    try {
                        maquina.setIdMaquina(Integer.parseInt(txt_id.getText().trim()));
                        maquina.setMarca(txt_marca.getText().trim());
                        maquina.setModelo(Integer.parseInt(txt_modelo.getText().trim()));
                        
                        if (tipomaquina.equalsIgnoreCase("Bulldozer")) {
                            maquina.setTipoMaquina("Bulldozer");
                        } else if (tipomaquina.equalsIgnoreCase("Excavadora")) {
                            maquina.setTipoMaquina("Excavadora");
                        } else if (tipomaquina.equalsIgnoreCase("Miniexcavadora")) {
                            maquina.setTipoMaquina("Miniexcavadora");
                        } else if (tipomaquina.equalsIgnoreCase("Retroexcavadora")) {
                            maquina.setTipoMaquina("Retroexcavadora");
                        } else if (tipomaquina.equalsIgnoreCase("Minicargador")) {
                            maquina.setTipoMaquina("Minicargador");
                        } else if (tipomaquina.equalsIgnoreCase("Motoniveladoras")) {
                            maquina.setTipoMaquina("Motoniveladoras");
                        } else if (tipomaquina.equalsIgnoreCase("Camiones articulados")) {
                            maquina.setTipoMaquina("Camiones articulados");
                        } 
                        
                        maquina.setFechaAdquisicion(java.sql.Date.valueOf(fecha));
                        maquina.setEstatus(estatus);

                        String precioTXT = "";
                        double Precio = 0.0;
                        precioTXT = txt_precio.getText().trim();
                        boolean aux = false;
                        /*
                            *si el usuario ingresa coma como punto decimal lo trasformamos a punto
                         */
                        for (int i = 0; i < precioTXT.length(); i++) {
                            if (precioTXT.charAt(i) == ',') {
                                String precioNuevo = precioTXT.replace(",", ".");
                                Precio = Double.parseDouble(precioNuevo);
                                aux = true;
                            }
                        }

                        // evaluamos la condicion
                        if (aux == true) {
                            maquina.setCostoRenta(Precio);
                        } else {
                            Precio = Double.parseDouble(precioTXT);
                            maquina.setCostoRenta(Precio);
                        }

                        if (controlmaquina.guardar(maquina)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado");

                        } else {
                            JOptionPane.showMessageDialog(null, "Error al guardar");
                        }

                    } catch (HeadlessException | NumberFormatException e) {
                        System.out.println("Error en: " + e);
                    }

                }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "La maquina ya existe");
            }
        }
        
    }//GEN-LAST:event_registrartxtMouseClicked

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        // Obtener el carácter ingresado por el usuario
    char c = evt.getKeyChar();
    
    // Obtener el texto actual del campo de ID
    String id = txt_id.getText();
    
    // Verificar que el carácter sea un dígito numérico y que la longitud actual del ID sea menor o igual a 9
    if (Character.isDigit(c) && id.length() < 10) {
        // Si se cumple, permitir el carácter ingresado en el campo
    } else {
        // Si no se cumple, consumir el carácter para evitar que se ingrese en el campo
        evt.consume();
    }
    }//GEN-LAST:event_txt_idKeyTyped

    private void txt_marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_marcaKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isLetter(c) || c == evt.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_marcaKeyTyped

    private void txt_modeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modeloKeyTyped
        // Obtener el carácter ingresado por el usuario
    char c = evt.getKeyChar();
    
    // Obtener el texto actual del campo de ID
    String id = txt_modelo.getText();
    
    // Verificar que el carácter sea un dígito numérico y que la longitud actual del ID sea menor o igual a 9
    if (Character.isDigit(c) && id.length() < 4) {
        // Si se cumple, permitir el carácter ingresado en el campo
    } else {
        // Si no se cumple, consumir el carácter para evitar que se ingrese en el campo
        evt.consume();
    }
    }//GEN-LAST:event_txt_modeloKeyTyped

    private void txt_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precioKeyTyped
   
    // Obtener el carácter ingresado por el usuario
    char c = evt.getKeyChar();
    
    // Obtener el texto actual del campo de precio
    String precio = txt_precio.getText();
    
    // Verificar que el carácter sea un dígito numérico, un punto o una coma, y que la longitud actual del precio sea menor o igual a 9 (7 dígitos antes del separador y 2 después)
    if ((Character.isDigit(c) || c == '.' || c == ',') && precio.length() <= 30) {
        // Si se cumple, permitir el carácter ingresado en el campo
        if (precio.indexOf('.') == -1 && precio.indexOf(',') == -1) {
            // El separador decimal no se ha ingresado aún, permitir cualquier carácter
        } else if (precio.indexOf('.') != -1) {
            // El separador decimal es un punto
            int separador = precio.indexOf('.');
            if (precio.length() - separador <= 2) {
                // Solo se han ingresado 1 o 2 dígitos después del punto, permitir el carácter ingresado en el campo
            } else {
                evt.consume();
            }
        } else if (precio.indexOf(',') != -1) {
            // El separador decimal es una coma
            int separador = precio.indexOf(',');
            if (precio.length() - separador <= 2) {
                // Solo se han ingresado 1 o 2 dígitos después de la coma, permitir el carácter ingresado en el campo
            } else {
                evt.consume();
            }
        }
    } else {
        // Si no se cumple, consumir el carácter para evitar que se ingrese en el campo
        evt.consume();
    }
    }//GEN-LAST:event_txt_precioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel pregistrar;
    private javax.swing.JLabel registrartxt;
    private com.toedter.calendar.JDateChooser txt_fecha;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){

        txt_id.setText("");
        txt_marca.setText("");
        txt_modelo.setText("");
        txt_fecha.setDateFormatString("");
        txt_precio.setText("");
        combotipo.setSelectedIndex(0);
    }
}
