/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import Controlador.Ctrl_Renta;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import Modelo.Renta;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class RentaVista extends javax.swing.JPanel {
    
    
    int darIdCliente =0;
    int id_cliente=0;
    int id_maquina=0;
    int id_operador=0;
    double rentamaquina=0;
    double rentaTotal=0;
    

    /**
     * Creates new form Renta
     */
    public RentaVista() {
        initComponents();
        CargarCombocliente();  
        CargarComboMaquina();
        CargarComboOperario();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBox_cliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_maquina = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ComboBox_operario = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombrecliente = new javax.swing.JTextField();
        txt_direccioncliente = new javax.swing.JTextField();
        txt_emailcliente = new javax.swing.JTextField();
        txt_telefonocliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        pfechainicial = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_fecha_entrega = new com.toedter.calendar.JDateChooser();
        ptotal = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_RentaTotal = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_marcamaquina = new javax.swing.JTextField();
        txt_modelomaquina = new javax.swing.JTextField();
        txt_estadomaquina = new javax.swing.JTextField();
        txt_costemaquina = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        pprecio = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_rentaUnitaria = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_nombreoperario = new javax.swing.JTextField();
        txt_direccionoperario = new javax.swing.JTextField();
        txt_emailoperario = new javax.swing.JTextField();
        txt_telefonooperario = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        pfechafinal = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        prenta = new javax.swing.JPanel();
        Boton_renta = new javax.swing.JLabel();
        txt_fecha_termino = new com.toedter.calendar.JDateChooser();
        prenta1 = new javax.swing.JPanel();
        Boton_total = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(780, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RENTA DE MAQUINARIA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cliente:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 57, 105, -1));

        ComboBox_cliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ComboBox_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_cliente.setBorder(null);
        ComboBox_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_clienteMouseClicked(evt);
            }
        });
        add(ComboBox_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 86, 160, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Maquina:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 143, 105, -1));

        ComboBox_maquina.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ComboBox_maquina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_maquina.setBorder(null);
        add(ComboBox_maquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 171, 160, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Operario:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 233, 105, -1));

        ComboBox_operario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ComboBox_operario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_operario.setBorder(null);
        add(ComboBox_operario, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 261, 160, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nombre:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 70, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Direccion:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Email:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 160, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Telefono:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 80, -1));

        txt_nombrecliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombrecliente.setBorder(null);
        txt_nombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreclienteActionPerformed(evt);
            }
        });
        add(txt_nombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 140, -1));

        txt_direccioncliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_direccioncliente.setBorder(null);
        add(txt_direccioncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 130, -1));

        txt_emailcliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emailcliente.setBorder(null);
        add(txt_emailcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 160, -1));

        txt_telefonocliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_telefonocliente.setBorder(null);
        add(txt_telefonocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 80, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 133, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 140, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 133, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 130, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 133, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 160, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 133, 0));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 80, 10));

        pfechainicial.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fecha de Entrega:");

        jSeparator7.setForeground(new java.awt.Color(255, 133, 0));

        txt_fecha_entrega.setDateFormatString("dd-MMMM-yyyy");

        javax.swing.GroupLayout pfechainicialLayout = new javax.swing.GroupLayout(pfechainicial);
        pfechainicial.setLayout(pfechainicialLayout);
        pfechainicialLayout.setHorizontalGroup(
            pfechainicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfechainicialLayout.createSequentialGroup()
                .addGroup(pfechainicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(pfechainicialLayout.createSequentialGroup()
                        .addGroup(pfechainicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pfechainicialLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_fecha_entrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pfechainicialLayout.setVerticalGroup(
            pfechainicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfechainicialLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_fecha_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        add(pfechainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 70));

        ptotal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total de la renta:");

        txt_RentaTotal.setBorder(null);

        jSeparator8.setForeground(new java.awt.Color(255, 133, 0));

        javax.swing.GroupLayout ptotalLayout = new javax.swing.GroupLayout(ptotal);
        ptotal.setLayout(ptotalLayout);
        ptotalLayout.setHorizontalGroup(
            ptotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptotalLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ptotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ptotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_RentaTotal)
                    .addComponent(jSeparator8))
                .addContainerGap())
        );
        ptotalLayout.setVerticalGroup(
            ptotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptotalLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_RentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        add(ptotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Tipo de maquinaria");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Modelo:");

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Estado:");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Coste Renta:");

        txt_marcamaquina.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_marcamaquina.setBorder(null);

        txt_modelomaquina.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_modelomaquina.setBorder(null);

        txt_estadomaquina.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_estadomaquina.setBorder(null);

        txt_costemaquina.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_costemaquina.setBorder(null);

        jSeparator11.setForeground(new java.awt.Color(255, 133, 0));

        jSeparator12.setForeground(new java.awt.Color(255, 133, 0));

        jSeparator13.setForeground(new java.awt.Color(255, 133, 0));

        jSeparator14.setForeground(new java.awt.Color(255, 133, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator11)
                        .addComponent(txt_marcamaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_modelomaquina)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13)
                    .addComponent(txt_estadomaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jSeparator14)
                    .addComponent(txt_costemaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_marcamaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_modelomaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_estadomaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_costemaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jSeparator12)
                    .addComponent(jSeparator13)
                    .addComponent(jSeparator14))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 500, 70));

        pprecio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Renta Unitaria:");

        txt_rentaUnitaria.setBorder(null);

        jSeparator9.setForeground(new java.awt.Color(255, 133, 0));

        javax.swing.GroupLayout pprecioLayout = new javax.swing.GroupLayout(pprecio);
        pprecio.setLayout(pprecioLayout);
        pprecioLayout.setHorizontalGroup(
            pprecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pprecioLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pprecioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pprecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_rentaUnitaria)
                    .addComponent(jSeparator9))
                .addContainerGap())
        );
        pprecioLayout.setVerticalGroup(
            pprecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pprecioLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_rentaUnitaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        add(pprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Nombre:");

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Direccion:");

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Email:");

        jLabel23.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Telefono:");

        txt_nombreoperario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombreoperario.setBorder(null);

        txt_direccionoperario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_direccionoperario.setBorder(null);

        txt_emailoperario.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_emailoperario.setBorder(null);

        txt_telefonooperario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_telefonooperario.setBorder(null);

        jSeparator16.setForeground(new java.awt.Color(255, 133, 0));

        jSeparator17.setForeground(new java.awt.Color(255, 133, 0));

        jSeparator18.setForeground(new java.awt.Color(255, 133, 0));

        jSeparator19.setForeground(new java.awt.Color(255, 133, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombreoperario, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jSeparator16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator17)
                    .addComponent(txt_direccionoperario, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_emailoperario, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jSeparator18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_telefonooperario)
                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreoperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_direccionoperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emailoperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefonooperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jSeparator17)
                    .addComponent(jSeparator18)
                    .addComponent(jSeparator19))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 560, -1));

        pfechafinal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Fecha de Termino:");

        jSeparator20.setForeground(new java.awt.Color(255, 133, 0));

        prenta.setBackground(new java.awt.Color(255, 133, 0));

        Boton_renta.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Boton_renta.setForeground(new java.awt.Color(255, 255, 255));
        Boton_renta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_renta.setText("Rentar");
        Boton_renta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_rentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_rentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_rentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout prentaLayout = new javax.swing.GroupLayout(prenta);
        prenta.setLayout(prentaLayout);
        prentaLayout.setHorizontalGroup(
            prentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_renta, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        prentaLayout.setVerticalGroup(
            prentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_renta, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        txt_fecha_termino.setDateFormatString("dd-MMMM-yyyy");

        javax.swing.GroupLayout pfechafinalLayout = new javax.swing.GroupLayout(pfechafinal);
        pfechafinal.setLayout(pfechafinalLayout);
        pfechafinalLayout.setHorizontalGroup(
            pfechafinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfechafinalLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfechafinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pfechafinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pfechafinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_fecha_termino, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jSeparator20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pfechafinalLayout.setVerticalGroup(
            pfechafinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfechafinalLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_fecha_termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(prenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        add(pfechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 200, 140));

        prenta1.setBackground(new java.awt.Color(255, 133, 0));

        Boton_total.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Boton_total.setForeground(new java.awt.Color(255, 255, 255));
        Boton_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_total.setText("Total");
        Boton_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_totalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_totalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_totalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout prenta1Layout = new javax.swing.GroupLayout(prenta1);
        prenta1.setLayout(prenta1Layout);
        prenta1Layout.setHorizontalGroup(
            prenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prenta1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_total, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        prenta1Layout.setVerticalGroup(
            prenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prenta1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(prenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_rentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_rentaMouseEntered
        prenta.setBackground(new Color (255, 160, 30));
    }//GEN-LAST:event_Boton_rentaMouseEntered

    private void Boton_rentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_rentaMouseExited
        prenta.setBackground(new Color(222, 137, 21));
    }//GEN-LAST:event_Boton_rentaMouseExited

    private void Boton_rentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_rentaMouseClicked
        // TODO add your handling code here:
        
        Renta renta = new Renta();
        Ctrl_Renta ctrl_Renta = new Ctrl_Renta();
        
        String fecha1;
        String fecha2;
        java.util.Date date = new java.util.Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
       
        
        if(txt_fecha_termino.getDate() == null){
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
        }else{
            fecha1 = f.format(txt_fecha_entrega.getDate());
            fecha2 = f.format(txt_fecha_termino.getDate());

            Date fechaInicio = txt_fecha_entrega.getDate();
            Date fechaFin = txt_fecha_termino.getDate();

            long diff = fechaFin.getTime() - fechaInicio.getTime();
            long diffDays = diff / (24 * 60 * 60 * 1000);

            rentaTotal = rentamaquina * (diffDays +1 );
            txt_RentaTotal.setText(String.valueOf(rentaTotal));
            
            try {
                renta.setCostoTotal(rentaTotal);
                renta.setIdCliente(id_cliente);
                renta.setIdOperario(id_operador);
                renta.setFechaInicio(java.sql.Date.valueOf(fecha1));
                renta.setFechaFin(java.sql.Date.valueOf(fecha2));
                renta.setIdMaquinaria(id_maquina);
                
                if(!ctrl_Renta.guardar(renta)){
                    JOptionPane.showMessageDialog(null, "Se realizo la renta");
                    Limpiar();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "No se realizo la renta");
                }
                
            } catch (HeadlessException | NumberFormatException e) {
            }
            
            
        }
        
        
        
    }//GEN-LAST:event_Boton_rentaMouseClicked

    private void txt_nombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreclienteActionPerformed

    private void ComboBox_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_clienteMouseClicked
        CargarCombocliente();
    }//GEN-LAST:event_ComboBox_clienteMouseClicked

    private void Boton_totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_totalMouseClicked
        // TODO add your handling code here:
        
        Renta renta = new Renta();
        Ctrl_Renta ctrl_Renta = new Ctrl_Renta();
        
        String fecha1;
        String fecha2;
        java.util.Date date = new java.util.Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
       
        
        if(txt_fecha_termino.getDate() == null){
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
        }else{
            fecha1 = f.format(txt_fecha_entrega.getDate());
            fecha2 = f.format(txt_fecha_termino.getDate());

            Date fechaInicio = txt_fecha_entrega.getDate();
            Date fechaFin = txt_fecha_termino.getDate();

            long diff = fechaFin.getTime() - fechaInicio.getTime();
            long diffDays = diff / (24 * 60 * 60 * 1000);

            rentaTotal = rentamaquina * (diffDays +1 );
            txt_RentaTotal.setText(String.valueOf(rentaTotal));
        }
        
    }//GEN-LAST:event_Boton_totalMouseClicked

    private void Boton_totalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_totalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_totalMouseEntered

    private void Boton_totalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_totalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_totalMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton_renta;
    private javax.swing.JLabel Boton_total;
    private javax.swing.JComboBox<String> ComboBox_cliente;
    private javax.swing.JComboBox<String> ComboBox_maquina;
    private javax.swing.JComboBox<String> ComboBox_operario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel pfechafinal;
    private javax.swing.JPanel pfechainicial;
    private javax.swing.JPanel pprecio;
    private javax.swing.JPanel prenta;
    private javax.swing.JPanel prenta1;
    private javax.swing.JPanel ptotal;
    private javax.swing.JTextField txt_RentaTotal;
    private javax.swing.JTextField txt_costemaquina;
    private javax.swing.JTextField txt_direccioncliente;
    private javax.swing.JTextField txt_direccionoperario;
    private javax.swing.JTextField txt_emailcliente;
    private javax.swing.JTextField txt_emailoperario;
    private javax.swing.JTextField txt_estadomaquina;
    private com.toedter.calendar.JDateChooser txt_fecha_entrega;
    private com.toedter.calendar.JDateChooser txt_fecha_termino;
    private javax.swing.JTextField txt_marcamaquina;
    private javax.swing.JTextField txt_modelomaquina;
    private javax.swing.JTextField txt_nombrecliente;
    private javax.swing.JTextField txt_nombreoperario;
    private javax.swing.JTextField txt_rentaUnitaria;
    private javax.swing.JTextField txt_telefonocliente;
    private javax.swing.JTextField txt_telefonooperario;
    // End of variables declaration//GEN-END:variables
    
    private void CargarCombocliente() {
    Connection cn = conexion.Conexion.conectar();
    String sql = "select * from clientes order by nombre asc";
    Statement st;

    try {

        st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        ComboBox_cliente.removeAllItems();
        ComboBox_cliente.addItem("Selecciona al Cliente");
        while (rs.next()) {
            String nombre = rs.getString("nombre");
            ComboBox_cliente.addItem(nombre);
        }
        
        cn.close();
    } catch (SQLException e) {
        System.out.println("Error al cargar el cliente");
    }
    
    ComboBox_cliente.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (ComboBox_cliente.getSelectedIndex() > 0) {
                String nombre_cliente = ComboBox_cliente.getSelectedItem().toString();
                
                EnviarDatosClienteSeleccionado(nombre_cliente);
            }
        }
    });
}

private void EnviarDatosClienteSeleccionado(String nombre_cliente) {
    try {
        Connection con = conexion.Conexion.conectar();
        PreparedStatement pst = con.prepareStatement(
                "select * from clientes where nombre = ?");
        pst.setString(1, nombre_cliente);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            id_cliente = Integer.parseInt(rs.getString("id_cliente"));
            txt_nombrecliente.setText(rs.getString("nombre"));
            this.txt_direccioncliente.setText(rs.getString("direccion"));
            txt_emailcliente.setText(rs.getString("email"));
            txt_telefonocliente.setText(rs.getString("telefono"));
            
        }
        con.close();

    } catch (SQLException e) {
        System.out.println("Error al seleccionar al cliente" + e);
    }
}

private void CargarComboMaquina() {
    Connection cn = conexion.Conexion.conectar();
    String sql = "select * from maquinaria order by marca asc";
    Statement st;

    try {

        st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        ComboBox_maquina.removeAllItems();
        ComboBox_maquina.addItem("Selecciona la maquina");
        while (rs.next()) {
            
            String tipo = rs.getString("marca");
            ComboBox_maquina.addItem(tipo);
            
        }
        
        cn.close();
    } catch (SQLException e) {
        System.out.println("Error al cargar la maquina");
    }
    
    ComboBox_maquina.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            if (ComboBox_maquina.getSelectedIndex() > 0) {
                String tipo_maquina = ComboBox_maquina.getSelectedItem().toString();
                EnviarDatosMaquinaSeleccionado(tipo_maquina);
                
            }
        }
    });
}

private void EnviarDatosMaquinaSeleccionado(String tipo_maquina) {
    try {
        Connection con = conexion.Conexion.conectar();
        PreparedStatement pst = con.prepareStatement(
                "select * from maquinaria where marca = ?");
        pst.setString(1, tipo_maquina);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            id_maquina= Integer.parseInt(rs.getString("id_maquinaria"));
            txt_marcamaquina.setText(rs.getString("tipo"));
            this.txt_modelomaquina.setText(rs.getString("modelo"));
            txt_estadomaquina.setText(rs.getString("estatus"));
            txt_costemaquina.setText(rs.getString("costo_renta_dia"));
            txt_rentaUnitaria.setText(Double.toString(rs.getDouble("costo_renta_dia")));
            rentamaquina= Double.parseDouble(rs.getString("costo_renta_dia"));
           
            
        }
        con.close();

    } catch (SQLException e) {
        System.out.println("Error al seleccionar la maquina" + e);
    }
}


private void CargarComboOperario() {
    Connection cn = conexion.Conexion.conectar();
    String sql = "select * from operarios order by nombre asc";
    Statement st;

    try {

        st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        ComboBox_operario.removeAllItems();
        ComboBox_operario.addItem("Selecciona el operario");
        while (rs.next()) {
            String nombre = rs.getString("nombre");
            ComboBox_operario.addItem(nombre);
        }
        
        cn.close();
    } catch (SQLException e) {
        System.out.println("Error al cargar el operario");
    }
    
    ComboBox_operario.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (ComboBox_operario.getSelectedIndex() > 0) {
                String nombre_operario = ComboBox_operario.getSelectedItem().toString();
                EnviarDatosOperarioSeleccionado(nombre_operario);
            }
        }
    });
}

private void EnviarDatosOperarioSeleccionado(String nombre_operario) {
    try {
        Connection con = conexion.Conexion.conectar();
        PreparedStatement pst = con.prepareStatement(
                "select * from operarios where nombre = ?");
        pst.setString(1, nombre_operario);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            id_operador = Integer.parseInt(rs.getString("id_operario"));
            System.err.println("El operario es: "+id_operador);
            txt_nombreoperario.setText(rs.getString("nombre"));
            this.txt_direccionoperario.setText(rs.getString("direccion"));
            txt_telefonooperario.setText(rs.getString("telefono"));
            txt_emailoperario.setText(rs.getString("email"));
            
        }
        con.close();

    } catch (SQLException e) {
        System.out.println("Error al seleccionar al operario" + e);
    }
}

private void Limpiar(){
    txt_rentaUnitaria.setText("");
    txt_RentaTotal.setText("");
    ComboBox_cliente.setSelectedIndex(0);
    ComboBox_maquina.setSelectedIndex(0);
    ComboBox_operario.setSelectedIndex(0);
}

}
